name: Update LeetCode Stats

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  permissions:
   contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get LeetCode Solved Count
        run: |
          curl -X POST https://leetcode.com/graphql \
          -H "Content-Type: application/json" \
          -d '{
            "query":"query userProblemsSolved($username: String!) { matchedUser(username: $username) { submitStatsGlobal { acSubmissionNum { difficulty count } } } }",
            "variables":{"username":"aravind628187"}
          }' > result.json

      - name: Install jq
        run: sudo apt-get install jq

      - name: Update stats.json
        run: |
          TOTAL=$(jq '.data.matchedUser.submitStatsGlobal.acSubmissionNum[0].count' result.json)

          echo "{
            \"leetcodeSolved\": $TOTAL
          }" > public/stats.json

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add public/stats.json

          git commit -m "Update LeetCode Stats" || exit 0

          git push