name: Update LeetCode Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch LeetCode Count
        run: |
          curl -X POST https://leetcode.com/graphql \
          -H "Content-Type: application/json" \
          -d '{
            "query":"query userProblemsSolved($username: String!) { matchedUser(username: $username) { submitStatsGlobal { acSubmissionNum { difficulty count } } } }",
            "variables":{"username":"aravind628187"}
          }' > result.json

      - name: Generate stats.json
        run: |
          TOTAL=$(jq '.data.matchedUser.submitStatsGlobal.acSubmissionNum[0].count' result.json)

          cat > public/stats.json <<EOF
          {
            "leetcodeSolved": $TOTAL,
            "hackerrankSolved": 25
          }
          EOF

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add public/stats.json

          git diff --staged --quiet || git commit -m "Update LeetCode Stats"

          git push